### ISSUE TITLE
Difficulty with build

### ISSUE THREAD

**Issue by robmoore** [SpinGo/op-rabbit#1]
I've run into two issues.
- The build.properties file has quotes around the sbt version number. With them, the build fails. Without, it works as expected.
- I'm not able to resolve the scoped-fixtures dependency:

```
    [warn] ==== SpinGo OSS: tried
    [warn]   http://spingo-oss.s3.amazonaws.com/repositories/releases/com/spingo/scoped-fixtures_2.11/0.4.0/scoped-fixtures_2.11-0.4.0.pom
    [warn] ==== Sonatype Releases: tried
    [warn]   http://oss.sonatype.org/content/repositories/releases/com/spingo/scoped-fixtures_2.11/0.4.0/scoped-fixtures_2.11-0.4.0.pom
    [info] Resolving jline#jline;2.12.1 ...
    [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
    [warn]  ::          UNRESOLVED DEPENDENCIES         ::
    [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
    [warn]  :: com.spingo#scoped-fixtures_2.11;0.4.0: not found
    [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
    [warn]  
    [warn]  Note: Unresolved dependencies path:
    [warn]      com.spingo:scoped-fixtures_2.11:0.4.0 (/home/rob/git/op-rabbit/project/Build.scala#L16)
    [warn]        +- com.spingo:op-rabbit-core_2.11:1.0.0-SNAPSHOT
sbt.ResolveException: unresolved dependency: com.spingo#scoped-fixtures_2.11;0.4.0: not found
```

In the later case, I try to follow the link to the pom file and get a NoSuchKey error from AWS.

**Comment by timcharper** [comment]
Rob,

I've pushed the scoped-fixtures dependency to spingo-oss. Can you try again and report?

I'm not sure why our experience with build.properties differences; which set version are you using?

**Comment by robmoore** [comment]
Thanks, Tim. That worked.

I'm using sbt 0.13.8.

**Comment by timcharper** [comment]
Okay; I'm using an earlier version; I'll upgrade and go with the quotes.

**Comment by timcharper** [comment]
And by earlier version, I mean:

``` sh
$ sbt --version
sbt launcher version 0.13.7
```

**Comment by robmoore** [comment]
FWIW, these docs show it without quotes: 

http://www.scala-sbt.org/0.13/tutorial/Combined+Pages.html#Setting+the+sbt+version

**Comment by timcharper** [comment]
Okay; great. I've went with the no quotes version. Thank you!
