### ISSUE TITLE
Conditional RecoveryStrategy Question

### ISSUE THREAD

**Issue by angusng** [SpinGo/op-rabbit#104]
Hi, I'm just wondering whether there is a way to decide what exception should be handled by RecoveryStrategy? I'd like to use the limitedRedeliver handler for certain scenario which retry should help on processing message (e.g. unstable network). But in a scenario of some "unrecoverable" exception (e.g. incorrect message structure), I want to put it into the deadletter right away. Is that possible? Thanks.

** In the context of AckedStream

**Comment by timcharper** [comment]
Hi, @angusng ! Sorry for the late reply. You've probably figured it out / moved on.

It is possible. `RecoveryStrategy`'s type signature was made to be completely composable for stuff like this and looks like this:

```
trait RecoveryStrategy extends ((String, Channel, Throwable) => Handler)
```

Which means, you could implement a new RecoveryStrategy, do your logic on the `Throwable`, and then delegate to another `RecoveryStrategy`. Something like this:

```
val redeliver = RecoveryStrategy.limitedRedeliver(...)

RecoveryStrategy { (queueName, channel, exception) =>
  if (condition(exception))
    redeliver(queueName, channel, exception)
  else
    extract(identity) { delivery =>
      val body = delivery.body
      // do your dead letter logic
      ack
    }
}

**Comment by jball606** [comment]
Do you have any real examples of this fully written out?  I can't seem to figure out how to do this from the code above.

**Comment by timcharper** [comment]
You need to import directives; see the implementation and imports here for inspiration: https://github.com/SpinGo/op-rabbit/blob/master/core/src/main/scala/com/spingo/op_rabbit/RecoveryStrategy.scala#L59
