### ISSUE TITLE
Can't connect to amqp

### ISSUE THREAD

**Issue by SergeyZharikhin** [SpinGo/op-rabbit#108]
I have an issue.
15:32:54.526 [such-system-akka.actor.default-dispatcher-5] ERROR com.thenewmotion.akka.rabbitmq.ConnectionActor - akka://such-system/user/$a/connection in Disconnected received Connect: can't connect to amqp://guest@{127.0.0.1:15672}:5672/foo, retrying in 10 seconds

and my application.conf has:

op-rabbit {
  connection {
    virtual-host = "foo"
    hosts = ["127.0.0.1"]
    username = "guest"
    password = "guest"
    port = 15672
    ssl = false
    connection-timeout = 3s
  }
}

**Comment by theshortcut** [comment]
My guess is that your port config should be `5672` rather than `15672` (which is just the default web ui port).

**Comment by SergeyZharikhin** [comment]
Thanks, theshortcut. It works with `5672`. my bad
