### ISSUE TITLE
NoSuchMethodError version1.6.0 and akka-actor version 2.4.8

### ISSUE THREAD

**Issue by brijeshkec11** [SpinGo/op-rabbit#111]
java.lang.NoSuchMethodError: akka.pattern.AskableActorRef$.$qmark$default$3$extension(Lakka/actor/ActorRef;Ljava/lang/Object;)Lakka/actor/ActorRef;
        at com.spingo.op_rabbit.Subscription.run(Subscription.scala:67)
        at com.spingo.op_rabbit.Subscription$.run(Subscription.scala:16)

Any help?

**Comment by timcharper** [comment]
Oh geez. I have no idea. 1.6.x was built with 2.4.8. Double check your dependencies? Clear your sbt cache?

**Comment by brijeshkec11** [comment]
Thanks timcharper for the reply.
Finally I found the issue. is was due to an older version if akka (akka-actor_2.11-2.3.10.jar) present in  Scala lib (/usr/share/scala/lib/akka-actor_2.11-2.3.10.jar)
I deleted the same and now I do not see this issue anymore.

looks like akka library is present when you install Scala using deb package.
please close this ticket.

**Comment by timcharper** [comment]
Glad you figured it out!
