### ISSUE TITLE
Hangs on closing if SubscriptionRef isn't initialized

### ISSUE THREAD

**Issue by SunPj** [SpinGo/op-rabbit#112]
I am using op-rabbit in my play app. I have following code to close rabbit connections.

```
  lifecycle.addStopHook { () =>
   subscriptionRef.closed
  }
```

But it hangs when I run my tests, I had a suspicion that it may be due to SubscriptionRef isn't initialized and I tried following code

```
  lifecycle.addStopHook { () =>
   subscriptionRef.initialized.map(_ => subscriptionRef.closed)
  }
```
It seems to work well. 

Is it correct way to close rabbit mq connections?

**Comment by timcharper** [comment]
`closed` doesn't do anything. Did you mean `close` ?
