### ISSUE TITLE
Received an Ack on non existing queue with existing exchange

### ISSUE THREAD

**Issue by delanst** [SpinGo/op-rabbit#113]
Hi,

I use oprabbit version 1.6.0. An environment variable for the queue name was wrongly set. When i tried to publish a message on that queue I received an Ack and not a Fail.  See publish code below

  val received = (
      rabbitControl ? Message.queue(
        event,
        queue = QueueName)
      ).mapTo[ConfirmResponse]

    val messageResponse = received map {
      case Message.Ack(id) => Success(1)
      case Message.Nack(id) => {
        val eventEx = new EventException(s"Received Nacj for event ${event}")
        logger error eventEx
        Failure(eventEx)
      }
      case Message.Fail(id, ex) => {
        val eventEx = new EventException(s"Received fail for ${event}")
        logger error eventEx
        Failure(eventEx)
      }
    }

Could someone try to simulate this or i am making a bad assumption?

**Comment by nikitapecasa** [comment]
Hi,

It's expected behaviour, see https://github.com/SpinGo/op-rabbit/issues/83.
