### ISSUE TITLE
HOCON environment substitutions-friendly hosts config

### ISSUE THREAD

**Issue by e-kolpakov** [SpinGo/op-rabbit#117]
Typesafe config HOCON format supports [substituting variables](https://github.com/typesafehub/config#uses-of-substitutions) from environment. However, it's not possible to use this feature with `op-rabbit.hosts`, since `op-rabbit.hosts` only supports array values, and it's not possible to put array value into environment var (AFAIK)

It is mentioned in [Usage](https://github.com/SpinGo/op-rabbit#usage) section, but with little emphasis, so it might be great to:

1. Either make the note more visible in readme
2. ... or, better though, add support for using comma-separated string for `hosts`

I might be able to invest some time to add that support, but I'd like to discuss it first and make sure this enhancement is not against design principles or any ongoing work.

**Comment by e-kolpakov** [comment]
@timcharper Hi! Could you please comment on this issue - in particular would the change to add comma-separated hosts config be welcome?

**Comment by timcharper** [comment]
You know, this really is a shame that there isn't a standard definition for specifying multiple hosts via the URL (zookeeper has the standard `zk://host1:port,host2:port/etc/etc`. I'd support the comma delimited change; it makes sense.

**Comment by e-kolpakov** [comment]
@timcharper Ok, I'll look into it.
