### ISSUE TITLE
2.0.0 only available for 2.11 on central

### ISSUE THREAD

**Issue by TrustNoOne** [SpinGo/op-rabbit#120]
I can't find it on `"SpinGo OSS" at "http://spingo-oss.s3.amazonaws.com/repositories/releases"` either

![image](https://user-images.githubusercontent.com/1575319/28966210-405fd55e-7915-11e7-8fcc-f49daa83bfa4.png)

**Comment by urcadox** [comment]
It's not on Sonatype OSS either. :(

**Comment by acjay** [comment]
2.0.0-rc1 is available, and 2.0.0 [appears to have no changes](https://github.com/SpinGo/op-rabbit/commit/d02045acef3c3bb7222437729affd63808adde89) other than the version bump. So I'm going to go ahead and use that, until 2.0.0 proper gets published.

**Comment by TrustNoOne** [comment]
the library seems pretty abandoned anyway

**Comment by shea-hawkins-zz** [comment]
@timcharper Do you have any ETA on this? We'd love to help with this library but it's not possible for us to compile 2.12 version on Maven.

**Comment by timcharper** [comment]
Thanks for bringing this to my attention; I am drowning in GitHub notifications and miss things. I re-published and released. You're right, 2.12-rc1 is the same as 2.12.
