### ISSUE TITLE
Version 2 changes?

### ISSUE THREAD

**Issue by urcadox** [SpinGo/op-rabbit#122]
Hello Tim, hello everyone,

As I don't see any changes in the README regarding v2 except for the compatibility matrix, I'm wondering if there actually were API changes? Do you intend publishing a migration guide and/or relevant API changes? What other changes should one be aware of?

Thank you for your answers and thank you for your work! :+1:

**Comment by urcadox** [comment]
So... I just tried to update to 2.0.0, from 1.6.0, on a (closed-source) project and... it looks like it's working; I did not get any errors nor deprecation warnings.

I guess I will just make sure that everything runs fine and eventually push the change. Still, I would very much like to know what warranted this major version bump.

**Comment by timcharper** [comment]
It was a major upgrade to an underlying library that warranted it, akka-rabbit-mq 4; upgrade which was necessary to support Scala 2.12
