### ISSUE TITLE
Co-maintainer wanted

### ISSUE THREAD

**Issue by timcharper** [SpinGo/op-rabbit#126]
Hi there! I am still supporting this project with the limited time I have. Even though I no longer use the library, I've been working to keep it up to date and compatible with the latest libraries.

Feature wise, the library seems pretty complete. Current responsibilities include fielding issues, approving merge requests, and publishing releases.

Let me know if you're interested in this project and want to help it continue!

Thanks

**Comment by DStranger** [comment]
Hello @timcharper,

I'm interested, this is an awesome library and we at NewMotion use it a lot.
Maybe @kiequoo would also be willing to help?

**Comment by timcharper** [comment]
Oh hey @DStranger oh man this is embarrassing. I typed up a response after I made you a collaborator! But anyways looks like I didn't send it. Anyways, I added you to the project! Thanks for being willing to help!

**Comment by DStranger** [comment]
Hey @timcharper, thanks!
I have a question though, how do we go about publishing new releases? I need some permissions, I suppose.

**Comment by timcharper** [comment]
@DStranger do you have a maven central account? I think I just need to grant you access.

BTW I just did a GitHub notification purge so I should be better about seeing these things in the future. I don't know why I didn't do that before. I had so much noise from GitHub that I couldn't see anything.

**Comment by timcharper** [comment]
(colleague pointed me to https://github.com/watching and it changed my life)

**Comment by DStranger** [comment]
@timcharper I've created a sonatype account - `d.kostyanoy`
I've also generated a PGP key and uploaded it to a public keyserver, I think I should be able to publish now.
I could try publishing new (snapshot?) version - 2.1.0 probably - with the latest library updates if you grant me access.

**Comment by timcharper** [comment]
Okay, I'll check on this right now.

**Comment by timcharper** [comment]
Looks like this is done via a ticket, which I've filed here: https://issues.sonatype.org/browse/MVNCENTRAL-3042

**Comment by DStranger** [comment]
@timcharper publishing a snapshot [has worked](https://oss.sonatype.org/content/repositories/snapshots/com/spingo/op-rabbit-core_2.12/2.1.0-SNAPSHOT/)!
I'll try to publish a proper RC to maven central later today.

**Comment by timcharper** [comment]
ೕ(˃̵ᴗ˂̵ ๑)

**Comment by timcharper** [comment]
＼\ ٩( ᐛ )و /／
