### ISSUE TITLE
Exclusive consumer property set explicitly to false

### ISSUE THREAD

**Issue by Kamill0** [SpinGo/op-rabbit#134]
Hi!

Recently in our project, we were digging into the possibility of creating an exclusive consumer in order to prevent from reading the same queue by more than one at a time (exclusive queues are not an option as we need them durable). 
According to both AMQP specification and Java API docs this is possible, and can be done via proper `channel.basicConsume` call (with exclusive argument set to true).

While looking into the op-rabbit sources, i noticed that this method has the exclusive parameter set explicity to false:
```scala
 def setupSubscription(channel: Channel, initialQos: Int): Option[String] = try {
    channel.basicQos(initialQos)
    Some(channel.basicConsume(
      subscription.queue.queueName,
      false,
      subscription.consumerTagPrefix.fold("")(prefix => s"$prefix-${ConsumerId()}"),
      false,
      false, // this here is the exclusive parameter
      properties.toJavaMap(subscription.consumerArgs),
      new DefaultConsumer(channel) {
        override def handleDelivery(
          consumerTag: String, envelope: Envelope, properties: BasicProperties, body: Array[Byte]): Unit = {
          self ! Delivery(consumerTag, envelope, properties, body)
        }
      }
    ))
  } catch {
    case ConnectionGoneException(_) =>
      None
  }
```

Before suggesting any PR i wanted to discuss, is there any specific reason this was done this way?

Thanks for the feedback in advance.

**Comment by mturlo** [comment]
Hi @Kamill0 - I seem to be facing a similar situation currently. With the lack of activity in this issue, have you found a workaround in the meantime?

**Comment by Kamill0** [comment]
Hi Maciej,
Unfortunately, soon after asking that question i quit my company and
therefore this project, so i am not able to provide you with a solution.
What i can tell you is that till the end of my time there i was not able to
figure out a suitable workaround for this issue.
Sorry i couldnt be of more help

**Comment by mturlo** [comment]
I hope it doesn't make me quit mine, then! Anyway, thanks a bunch for the swift reply, cheers.

**Comment by timcharper** [comment]
I think I would go about it by adding a parameter to `consume`, and then threading the value through to BoundConsumerDefinition etc.

**Comment by mturlo** [comment]
Thanks for the input, @timcharper. Will put together a PR in a minute.
