### ISSUE TITLE
Incorrect log message

### ISSUE THREAD

**Issue by borice** [SpinGo/op-rabbit#140]
I'm noticing a console log message reading: 

> [INFO] [05/23/2018 22:45:54.766] [rabbitmq-akka.actor.default-dispatcher-4] [akka://rabbitmq/user/$a/connection] akka://rabbitmq/user/$a/connection connected to amqp://admin@{my.host.name:1503}:5672//

This is incorrect. My `application.conf` has:
```
connection {
        virtual-host = "/"
        hosts = ["my.host.name"]
        username = "admin"
        password = "whatever"
        port = 1503
        ssl = false
        connection-timeout = 3s
    }
```
So it seems to me the correct URI for the connection should be:
`amqp://admin@my.host.name:1503/` rather than `amqp://admin@{my.host.name:1503}:5672//`

I know port 1503 is non-standard, but there's a conflict on 5672.

**Comment by DStranger** [comment]
Hello @borice!
I think a similar issue already exists: #137
