### ISSUE TITLE
is there a way to publish the String of an already serialized object as-is?

### ISSUE THREAD

**Issue by gknauth** [SpinGo/op-rabbit#143]
rabbitControl ! Message.topic(json, routingKey, exchange = outExchange)

`json` is a String that already looks like:  `{"foo": "a", "bar": "b", ...}`

When I publish this json String, the receiver gets:  `"{\"foo\": \"a\", \"bar\": \"b\", ...}"`
(including the starting & ending quotation marks.

If what I am given is a String of an already serialized object, is there a way I can publish this string using `op-rabbit` without the extra quoting?

**Comment by timcharper** [comment]
Hey there @gknauth! Two options:

1. Use UTF8StringMarshaller (downside: sets content-type to `text/plain`)
2. Create a custom Marshaller:

```
import java.nio.charset.StandardCharsets.UTF_8

case class ContentTypedUTF8StringMarshaller(contentType: String) extends RabbitMarshaller[String] with RabbitUnmarshaller[String] {
  protected val contentEncoding = Some(UTF_8.name)
  def marshall(value: String) =
    value.getBytes(UTF_8)

  def unmarshall(value: Array[Byte], contentType: Option[String], charset: Option[String]) =
    new String(value, charset.map(Charset.forName).getOrElse(UTF_8))
}
```

**Comment by gknauth** [comment]
Thanks!  Now just trying to figure out how to use [specify use of] the custom Marshaller.

**Comment by gknauth** [comment]
I think I figured that last bit out (from preceding comment).  I did the following, and it worked.  Thanks again!

    val outputMarshaller = ContentTypedUTF8StringMarshaller("application/json")
    ...
    rabbitControl ! Message.topic(json, routingKey, exchange = outExchange)(outputMarshaller)
