### ISSUE TITLE
Exchange type

### ISSUE THREAD

**Issue by dantodor** [SpinGo/op-rabbit#145]
Is there an example somewhere on how to work with various exchange types ? 
I see in reference.conf that you can declare the exchange name, but not the type. How would you define a topic or a header exchange ?
Thanks!

**Comment by DStranger** [comment]
Hi @dantodor,

`op-rabbit` provides a DSL for defining exchanges and binding queues to them, examples can be found in the README - [this is how you subscribe to a topic](https://github.com/SpinGo/op-rabbit#set-up-a-consumer-topic-subscription).
