### ISSUE TITLE
Connection/channel pool

### ISSUE THREAD

**Issue by amsjavan** [SpinGo/op-rabbit#149]
I want to make a lot of subscription.
- Is it possible to make some subscriptions with one channel?
- Is there any solution to have channel pool or something like that?

**Comment by timcharper** [comment]
No, you’ll need to allocate a pool of rabbit control actors and implement
pooling logic yourself.

**Comment by amsjavan** [comment]
Connection pool is done with rabbit control, How about channel pooling?

**Comment by timcharper** [comment]
Same. No pooling logic in this library :)

**Comment by amsjavan** [comment]
Is it a good idea to implement it?

**Comment by timcharper** [comment]
I don't think it makes sense to put it in the library, but perhaps as an
add on?
