### ISSUE TITLE
Support for consuming of messages different types

### ISSUE THREAD

**Issue by navoloch** [SpinGo/op-rabbit#166]
Would be great to provide support for consuming of different type messages from one queue (Or provide an example in read.me since I could not find it):
```
 Subscription.run(rabbitControl) {
    import Directives._
    channel() {
      consume(queue("queue")) {
        body(as[TypeA]) { abc => ack }
        body(as[TypeB]) { abc => ack }
      }
    }
  }
```

**Comment by timcharper** [comment]
Just consume as byte array and implant your own logic to dispatch the serializer?

**Comment by navoloch** [comment]
@timcharper Thanks, for replying. That what I actually did at the end (wrapped handlers for different types into future, combined them with `recoverWith` and passed it to `ack` method).

Could it be left as an enhancement? or just closed?

**Comment by timcharper** [comment]
Let's close it :)
