### ISSUE TITLE
Add missing stream operations

### ISSUE THREAD

**Issue by ghost** [SpinGo/op-rabbit#17]
There are several methods that "plain" streams have, but acked streams don't.
Some examples:
Source.via / Flow.via
Source.mapMaterializedValue

There are probably more I'm missing, these are just the ones I encountered.

**Comment by ghost** [comment]
I'll probably add some of them (at least the ones I need) sometime soon (assuming nothing more urgent pops up).

**Comment by timcharper** [comment]
Great point; I looked at your fork and didn't see any progress on these items; I'll implement the ones you've mentioned as they are easy.

**Comment by timcharper** [comment]
Implemented in 8659cd79b4a571a5253ee3040531c720bafdbd39
