### ISSUE TITLE
More controllable logging

### ISSUE THREAD

**Issue by salex89** [SpinGo/op-rabbit#19]
Is there any way to control the logs being spit out into the console? There are numerous lines printed directly, obviously with println, not using the logger. Things like: "handleDelivery 1", "I have ack 1", or something like "You jerk! 312 NO_ROUTE". I almost suspect the third one should be an exception of some sort. I tried to find it in the code, but no luck.

**Comment by timcharper** [comment]
Thank you for reporting,

Please update to M13, which does not include my shameful debugging code.
