### ISSUE TITLE
topicExchangeName needs to be more configurable

### ISSUE THREAD

**Issue by vbhavsar** [SpinGo/op-rabbit#28]
The only way to set the topicExchangeName is by having a op-rabbit.topic-exchange-name config in application.resources. This should be more flexible by allowing clients to pass in a config or the string itself. All of our configuration is scoped by environment so we will never have a top-level op-rabbit.topic-exchange-name. We will have **dev**.op-rabbit.topic-exchange-name, **prod**.op-rabbit.topic-exchange-name, etc.

See https://github.com/SpinGo/op-rabbit/blob/master/core/src/main/scala/com/spingo/op_rabbit/RabbitControl.scala#L18

**Comment by timcharper** [comment]
I can't help but think that this is solving a problem by adding another layer of indirection. Why won't you ever have a top-level configuration?
What problem does this solve for you by prefixing all of your configuration by your responding environment?

**Comment by timcharper** [comment]
What it help if it recognized and read the value from a system property?

**Comment by vbhavsar** [comment]
I was able to work around it by following directions to override the default exchange name.

As for your first question, we have setup a structure similar to [this](http://stackoverflow.com/a/21608053/152229).

Though I think my request will be useful, since there is a workaround, I will close the issue. Thanks for your responses!
