### ISSUE TITLE
Add ability to change the exchange type on producer

### ISSUE THREAD

**Issue by slevine** [SpinGo/op-rabbit#29]
Wondering if there is a way for us to specify the exchange type on the producing side?  We have figured out how to do it on the Consumer side via `consume(OurBinding(..))` and `OurBinding()` sets up a different _type_ of exchange via `channel.exchangeDeclare(.., TYPE, ..)`.

**Comment by timcharper** [comment]
Hi @slevine - this is certainly possible. But, can you help me understand a little more about your use case? Why do you feel like this is important?

The `Publisher` class is not declared as final, so you could extend it that way.

``` scala
class DeclaringPublisher(routingKey: String, topicBinding: TopicBinding) extends Publisher(topicBinding.exchange.exchangeName, routingKey) {
  private var declared: Boolean = false
  override def apply(c: Channel, data: Array[Byte], properties: BasicProperties): Unit = {
    if (! declared) synchronized {
      if ( ! declared ) {
        topicBinding.declare(c)
        declared = true
      }
    }
    super.apply(c, data, properties)
  }
}
```

Then:

``` scala
val declaringPublisher = DeclaringPublisher("my.topic", TopicBinding(...))
Message(declaringPublisher, data)
```

---

Another option, if you want to just declare the topic, but not send a message:

``` scala
class EagerDeclare(definition: QueueDefinition) extends MessageForPublicationLike {
  private val _declared: Promise[Unit]
  val declared = _applied.future
  def apply(c: Channel): Unit =
    _declared.complete(Try(definition.declare(c)))
}

val declaration = EagerDeclare(TopicBinding(...))
rabbitControl ! declaration
declaration.declared.foreach { _ =>
  // ready for action
}
```

Both of these are kind of hacks, granted. If I can learn more about what your problem is, we can come up with a better solution and perhaps get it implemented before the RC label comes off.

**Comment by timcharper** [comment]
That may not be the best approach; it will just ensure that the exchange is declared on first message published.

If I can learn more about what your problem is, maybe we can come up with a better solution.

**Comment by timcharper** [comment]
Another option, if you want to just declare the topic, but not send a message:

```scala
class EagerDeclare(definition: QueueDefinition) extends MessageForPublicationLike {
  private val _declared: Promise[Unit]
  val declared = _applied.future
  def apply(c: Channel): Unit =
    _declared.complete(Try(definition.declare(c)))
}

**Comment by slevine** [comment]
Thanks for the quick reply @timcharper -- really appreciate it.  The main reason it is important to us is because we are not using standard exchange types, and some of the time, the producer will bind before the consumer, so we needed a mechanism to change the ex type when the producer binds.

**Comment by timcharper** [comment]
Okay, the obvious solution here would be to allow you to pass a QueueDefinition or an ExchangeDefinition to your message publisher, and having said definition lazily apply.

Do you think that will solve it well enough, or can you think of a more enlightened way to solve it?

**Comment by timcharper** [comment]
@slevine please see `v1.0.0-RC4`, which should support the case you need. There was an already implemented feature that was somewhat similar to it, so I made the solution more general to apply to yours, also.

From [The Upgrading Wiki Page](https://github.com/SpinGo/op-rabbit/wiki/Upgrading):

``` scala
val factory = Message.factory(
  Publisher.queue(
    Queue("ahora-existe")))

val factory = Message.factory(
  Publisher.exchange(
    Binding.topic(
      Queue("ahora-existe", topics = List("los.nachos.*")))))
```
