### ISSUE TITLE
Reply with `message.uuid`

### ISSUE THREAD

**Issue by timcharper** [SpinGo/op-rabbit#30]
Replying with `true` is less than useful when one actor is publishing a message via `!`.

Modify it to respond with `Message.Confirmation(msg.uuid)` (and add a Message UUID property to every `Message`)

**Comment by timcharper** [comment]
@theshortcut WDYT?

https://github.com/SpinGo/op-rabbit/commit/ack-publisher-confirm

**Comment by theshortcut** [comment]
Looks good to me!
