### ISSUE TITLE
Installing with gradle?

### ISSUE THREAD

**Issue by xanderdunn** [SpinGo/op-rabbit#33]
I have a project that uses gradle.  I'd expect to be able to install it as a dependency just as any other.  In build.gradle: 

```
    repositories {
        maven {
            url "http://spingo-oss.s3.amazonaws.com/repositories/releases"
        }
    }

    dependencies {
        compile "com.spingo:op-rabbit-core:1.0.0"                  // rabbitMQ client
    }
```

I get: 

``` bash
Could not resolve all dependencies for configuration ':common:compile'.
> Could not find com.spingo:op-rabbit-core:1.0.0.
  Searched in the following locations:
      https://repo1.maven.org/maven2/com/spingo/op-rabbit-core/1.0.0/op-rabbit-core-1.0.0.pom
      https://repo1.maven.org/maven2/com/spingo/op-rabbit-core/1.0.0/op-rabbit-core-1.0.0.jar
      file:/Users/admin/.m2/repository/com/spingo/op-rabbit-core/1.0.0/op-rabbit-core-1.0.0.pom
      file:/Users/admin/.m2/repository/com/spingo/op-rabbit-core/1.0.0/op-rabbit-core-1.0.0.jar
      https://jcenter.bintray.com/com/spingo/op-rabbit-core/1.0.0/op-rabbit-core-1.0.0.pom
      https://jcenter.bintray.com/com/spingo/op-rabbit-core/1.0.0/op-rabbit-core-1.0.0.jar
      http://spingo-oss.s3.amazonaws.com/repositories/releases/com/spingo/op-rabbit-core/1.0.0/op-rabbit-core-1.0.0.pom
      http://spingo-oss.s3.amazonaws.com/repositories/releases/com/spingo/op-rabbit-core/1.0.0/op-rabbit-core-1.0.0.jar
```

I'm surprised this doesn't work.  The error message itself appears to show exactly the files it should be looking for.  I suspect I've simply gotten something small wrong in my gradle build settings.

**Comment by timcharper** [comment]
Sorry you're having troubles getting this to work!

You're going to need to include the Scala-version in the package name in order for this to work (since Scala is not bin compat between 2.10 and 2.11, separate artifacts are deployed, compiled against each).

For Scala 2.11, you need grade to look here:

https://spingo-oss.s3.amazonaws.com/repositories/releases/com/spingo/op-rabbit-core_2.11/1.0.0/op-rabbit-core_2.11-1.0.0.pom

Try updating your build.grade as to the following:

```
    repositories {
        maven {
            url "http://spingo-oss.s3.amazonaws.com/repositories/releases"
        }
    }

    dependencies {
        compile "com.spingo:op-rabbit-core_2.11:1.0.0"                  // rabbitMQ client
    }
```

**Comment by xanderdunn** [comment]
@timcharper That did it!  Thanks!  

Now I see all my other dependencies have an _2.11 as well.

**Comment by timcharper** [comment]
Great!

I'm working on an activator tutorial; If you can give me signal of anything that you found difficult to learn learn, it would be a great help and I could tune the tutorial accordingly.

**Comment by xanderdunn** [comment]
@timcharper Sure, I will!  I'm diving into it for the first time now.

**Comment by angusng** [comment]
Hi @timcharper , it seems that latest version 1.6.0 does not appear in the repository yet. Would you be able to check?

repositories {
    maven {
        url "http://spingo-oss.s3.amazonaws.com/repositories/releases"
    }
}

dependencies {
    compile 'com.spingo:op-rabbit-core_2.11:1.6.0'
    compile 'com.spingo:op-rabbit-akka-stream_2.11:1.6.0'
}

Thanks.

**Comment by timcharper** [comment]
You're right! Try again now?

**Comment by angusng** [comment]
It's all good now. Thanks.
