### ISSUE TITLE
Some Setup Questions

### ISSUE THREAD

**Issue by xanderdunn** [SpinGo/op-rabbit#34]
I'm serializing my classes with [protobuf](https://github.com/SandroGrzicic/ScalaBuff), so I don't intend to use any of the provided JSON tools.  

I have:

``` scala
  implicit val actorSystem = ActorSystem("controller-system")
  val rabbitControl = actorSystem.actorOf(Props[RabbitControl])

  val subscriptionRef = Subscription.run(rabbitControl) {
    import Directives._
    channel(qos = 3) {  // Process up to 3 concurrent messages at once
      consume(topic(queue("controller-message-queue"), List("actions-topic.#"))) {
        (body(as[Action]) & routingKey) { (action, key) =>
          print(s"Action '${action.value}' was received over '${key}'.\n")
          ack
        }
      }
    }
  }
```

where `Action` is my protobuf generated class.  On compile, I get: 

``` bash
MessagingControllerModule.scala:24: could not find implicit value for parameter um: com.spingo.op_rabbit.RabbitUnmarshaller[ai.osaro.traits.Types.Action]
        (body(as[Action]) & routingKey) { (action, key) =>
                ^
```

What's necessary for it to be able to handle a custom class?

Unrelated, where does op-rabbit look for the application.config?

**Comment by timcharper** [comment]
re: protobuffs, you'll need to implement your own serialization adapter. Just follow the pattern here:

https://github.com/SpinGo/op-rabbit/blob/master/addons/play-json/src/main/scala/com/spingo/op_rabbit/PlayJsonSupport.scala

Then, import the implicit methods you define in said object, and you should be able to deserialize.

Re: where `application.conf`, op-rabbit uses TypeSafe Config (https://github.com/typesafehub/config). And you should too. It's fantastic and there isn't a good reason to use anything else.

Typesafe config looks in `src/main/resources/application.conf`.

**Comment by timcharper** [comment]
Also, if you'd prefer, you can just get use `body(as[Array[Byte]])` and get a byte-array, which you can manually feed to your deserializer.

The implicit format adapter is noticeably shorter, though.

**Comment by ticofab** [comment]
Hey @timcharper , maybe this is a noob question but -- I am only able to use the PlayJsonSupport if I define both case class and implicit format in the same object where the channel is open (with body(...)). If they're not in the same file, I get the error

```
Error:(26, 17) could not find implicit value for parameter um: com.spingo.op_rabbit.RabbitUnmarshaller[xx.yyyy.User]
        (body(as[User]) & routingKey & exchange) {
                ^
```

maybe I need to explicitly pass some implicit to the body directive? Thanks.
