### ISSUE TITLE
Example for Java users

### ISSUE THREAD

**Issue by FrEaKmAn** [SpinGo/op-rabbit#35]
Hi

Can you please also add example for Java users? I'm not really sure how to use Subscription.run(...).

Edit: previous question was for Java Play, now only Java example.

**Comment by timcharper** [comment]
I've never written a Play app before! @mpolichette or @theshortcut, how goes your Play effort? Have you guys integrated the library in Play yet?

**Comment by FrEaKmAn** [comment]
I apologize, when I saw Akka, I somehow connected it with Play, but of course that is not correct.

I changed the issue to only include Java example.

**Comment by timcharper** [comment]
Sorry, Java interop isn't a thing for this library. I don't think it'd be very ergonomic.
