### ISSUE TITLE
Binding queues to direct exchange

### ISSUE THREAD

**Issue by kostyaev** [SpinGo/op-rabbit#37]
Hi! Seems like there is no possibility to bind queue to direct exchange by means of this library (we can do this by using rabbitmq client), currently we can only bind queues to topic, fanout and header exchanges. Although we can still overcome this problem by using topic exchange, but I guess this will make an impact on the performance due to more complex routing logic. Is this feature in the todo list?

**Comment by timcharper** [comment]
It is supported. But.... Looks like there isn't a way presently to specify the direct exchange! That's easy to add. I'll add it quickly and ship another release.
