### ISSUE TITLE
How can you set the message to be persistent?

### ISSUE THREAD

**Issue by raymatos** [SpinGo/op-rabbit#4]
See Title

**Comment by timcharper** [comment]
Great point; it's lacking right now. I'm in the process of refactoring the message code (implementing message confirms), and will provide a way to specify it. Any vote on how you'd like to see it implemented?

**Comment by timcharper** [comment]
Also, what are your thought on message persistence being the default?

**Comment by raymatos** [comment]
I think that it should be passed in with the message. And I do think it should be enabled by default.  

—

**Comment by timcharper** [comment]
I've published a snapshot version with the change; want to give it a spin? I'll soon roll out M3 after I finish updating documentation. I did two substantial changes in one commit and that's crappy, but they're somewhat related as it has to do with message handling.

Changes are in this commit: https://github.com/SpinGo/op-rabbit/commit/ba29a1407d5b776c9a751886c67ccd0c182e3f0d

**Comment by timcharper** [comment]
ba29a1407d5b776c9a751886c67ccd0c182e3f0d
