### ISSUE TITLE
Config for additional queue names

### ISSUE THREAD

**Issue by nnthnn** [SpinGo/op-rabbit#41]
It would be nice to be able to custom the names of the queues that are used to retry / abandon messages.

**Comment by timcharper** [comment]
Good suggestion; I'd prefer to make it somewhat uniform. Would it suffice to have a general configurable prefix?

**Comment by timcharper** [comment]
Or, perhaps a format string?

**Comment by nnthnn** [comment]
I'm open to whatever you think is best. The reason I put an issue in, is because my SysOps guy create my rabbit user with permissions like `^queueName.*$` for configure/read/write. So, without getting his help I could only created a postfix set of queue names but not the standard prefix ones. 

Though, it might be nice to override the names completely just for unforeseen circumstances.

**Comment by timcharper** [comment]
Flexibility usually leads to complexity. If a configurable prefix suffices, then I think that's what should be done.

**Comment by timcharper** [comment]
This was addressed with 96a6879decad34ea233d39e7e5bbb0a671d65f17
