### ISSUE TITLE
Document process for connecting to 2 different vhosts

### ISSUE THREAD

**Issue by raymatos** [SpinGo/op-rabbit#44]
How would i connect to 2 different vhost? 

If using the rabbitmq java lib, i would just setup 2 different connection factories.  How can i do something like that with op rabbit

**Comment by timcharper** [comment]
http://spingo-oss.s3.amazonaws.com/docs/op-rabbit/current/index.html#com.spingo.op_rabbit.RabbitControl

The RabbitControl actor accepts a connectionParams data structure. You would need to instantiate multiple rabbitControl actors.

``` scala

val config = ConfigFactory.load()

val rabbitVHost1 = actorSystem.actorOf(
  new RabbitControl(
    ConnectionParams.fromConfig(
      config.getConfig("vhost1"))))
val rabbitVHost2 = actorSystem.actorOf(
  new RabbitControl(
    ConnectionParams.fromConfig(
      config.getConfig("vhost2"))))
```

Something like that.

There are multiple ways to construct connectionParams; op-rabbit's opinion is that you should just use typesafe config, and you should use it's naming convention for parameter names, but you can pass it different config addresses to have a single application connect in multiple ways.

**Comment by timcharper** [comment]
https://github.com/SpinGo/op-rabbit/wiki/Cookbook
