### ISSUE TITLE
Silent failures with an existing queue

### ISSUE THREAD

**Issue by unthingable** [SpinGo/op-rabbit#45]
`val opRabbitVersion = "1.1.2"`

Scenario:

```
  val subscriptionRef = Subscription.run(rabbitControl) {
    channel(qos = 1) {
      consume(
        topic("foo", List("#"), exchange = "some_exchange")
      ) {....
```

If the queue does not exist, `op-rabbit` creates it, all is well. Creating the queue manually (via the management plugin) works too. 

However, creating the same queue manually with `x-max-length:10000` and then starting the Subscription results in messages not being consumed. No errors reported.

**Comment by unthingable** [comment]
Nevermind, just  found `def passive[T <: Concreteness](binding: QueueDefinition[T]):` which looks like exactly what I need. 

The ask is therefore reduced to having this mentioned in the documentation. :)

**Comment by timcharper** [comment]
Resolved by 9984d722e81c0858c227acc9eb1cc0a207ad9756. Thanks for the report, and sorry about this! What a terrible issue to encounter.

**Comment by timcharper** [comment]
Release v1.1.3 includes the fix.

**Comment by timcharper** [comment]
#46
