### ISSUE TITLE
Declaring an exchange through op-rabbit

### ISSUE THREAD

**Issue by iravid** [SpinGo/op-rabbit#47]
Hey, thanks for the great library! 

What's the recommended way of declaring an exchange using RabbitMQ's Java driver methods through the RabbitControl interface? Couldn't find any mention of this usecase.

To clarify - this is a publisher usecase; I don't require subscription/consumer functionality.

**Comment by timcharper** [comment]
You can provide an exchange definition to a publisher, and it will materialize it on first publish. Note, that materialization happens on first message publication per publisher instance, so you'll want to consider reusing publisher instances.

```
val publisher = Publisher.topic("topic.to.publish", Exchange.topic("chatty-cathy"))
for { data <- itemsForPublication } yield {
  (rabbitControl ? Message(data, publisher)).mapTo[Message.ConfirmResponse]
}
```

**Comment by iravid** [comment]
Thanks for the answer, Tim. I ran into another limitation - we use RabbitMQ's x-consistent-hash plugin (https://github.com/rabbitmq/rabbitmq-consistent-hash-exchange); this type is not defined in the `Exchange` enumeration. 

I'll gladly send a PR with the additional `Exchange.consistentHash` method and enum value.

Does this sound like an acceptable solution or would you prefer to drop the type parameter from the Exchange trait and allow users to pass in the exchange type as a string?

**Comment by timcharper** [comment]
Neat! Open up a new issue for it?

**Comment by iravid** [comment]
:+1:
