### ISSUE TITLE
How to set VirtualHost in config

### ISSUE THREAD

**Issue by mhabegger** [SpinGo/op-rabbit#5]
How would I set a virtual host to use ?
The ConnectionParams.scala supports VirtualHost but the `fromConfig` does not set it.

**Comment by timcharper** [comment]
I'll add it. Thanks for the request! Any vote on what to call the parameter? Leaning towards `virtual-host` to follow the naming convention of ConnectionFactory. (and hyphens to follow [idiomatic key naming conventions](http://doc.akka.io/docs/akka/snapshot/general/configuration.html) used in Akka)

**Comment by mhabegger** [comment]
Great !
As you suggested `virtual-host` fits best.

**Comment by timcharper** [comment]
I've published a snapshot version with the change; want to give it a spin? I'll soon roll out M3 after I finish updating documentation.
