### ISSUE TITLE
Declaring exchanges of types that aren't modeled by op-rabbit

### ISSUE THREAD

**Issue by iravid** [SpinGo/op-rabbit#51]
Example usecase - support for https://github.com/rabbitmq/rabbitmq-consistent-hash-exchange.

Two suggested solutions I could think of:
1. Add the exchange type to the `Exchange` enumeration;
2. Drop the type parameter from `Exchange` and `ExchangeImpl`; maintain the `Exchange.{topic,fanout,...}` but also provide an additional method that allow users of op-rabbit to pass custom strings as the `kind` parameter

**Comment by timcharper** [comment]
It already is possible! `Exchange.Value` isn't sealed, so you can provide your own Enums.

```
val xConsistentHashKind = new Exchange.Value {
  val id = 5
  override def toString = "x-consistent-hash"
}

class XConsistentHashExchange(val exchangeName: String) extends Exchange[xConsistentHashKind.type] {
  def declare(channel: com.rabbitmq.client.Channel): Unit = ???
}
```

You can instantiate XConsistentHashExchange and provide it anywhere a Concrete exchange is accepted.

**Comment by iravid** [comment]
Oh nice! Thanks!
