### ISSUE TITLE
op-rabbit-akka-stream-2.0 module cannot be resolved 

### ISSUE THREAD

**Issue by aomalov** [SpinGo/op-rabbit#54]
Using "SpinGo OSS" at "http://spingo-oss.s3.amazonaws.com/repositories/releases"

**Comment by timcharper** [comment]
http://spingo-oss.s3.amazonaws.com/repositories/releases/com/spingo/op-rabbit-akka-stream-2-0_2.11/1.2.0/op-rabbit-akka-stream-2-0_2.11-1.2.0.pom exists; what's the full URL that's failing to resolve?

**Comment by aomalov** [comment]
Hi, @timcharper !
This POM url helped me a lot. 
op-rabbit-akka-stream-2.0 module is not resolved in SBT with IntelliJ15, while
op-rabbit-akka-stream-2-0 is resolved perfectly.
For me, looking at the docs - it was not straightforward (that the dot turns in repo into dash) - that's why I thought - some spelling is not ok - and - found a grammar thing :)

Thanks for your quick help !
