### ISSUE TITLE
Error handling in play json unmarshall

### ISSUE THREAD

**Issue by laverton** [SpinGo/op-rabbit#55]
When conversion from JSON to case class in the PlayJsonSupport unmarshall function fails, the error is not handled very well:
java.util.NoSuchElementException: JsError.get
Is there any way to handle the error properly, and for example retrieve the contents of the JsError?

**Comment by timcharper** [comment]
That's awful, @laverton . Must have been a horrible experience finding out what was going on. The offending code is here:

https://github.com/SpinGo/op-rabbit/blob/master/addons/play-json/src/main/scala/com/spingo/op_rabbit/PlayJsonSupport.scala#L55

This should definitely match the JsResult and, if erroneous, unwrap the error and throw it.

**Comment by timcharper** [comment]
https://github.com/SpinGo/op-rabbit/commit/9fd952aa7b362cab0fc8260a8adb43f3058fe484

**Comment by timcharper** [comment]
1.2.1 was released with a fix.
