### ISSUE TITLE
Document RecoveryStrategy

### ISSUE THREAD

**Issue by raymatos** [SpinGo/op-rabbit#57]
How do you set the Recovery Strategy like retry limit, delay,  onAbandon, name of abandon queue, etc.

I was not able to find much on this.

**Comment by timcharper** [comment]
Hi @raymatos 

You set an implicit RecoveryStrategy when you define your consumer.

An example can be seen here:

https://github.com/SpinGo/op-rabbit/blob/641ff38bc2618425fd0862e76c97dfb0a47263f7/core/src/test/scala/com/spingo/op_rabbit/consumerSpec.scala#L136

**Comment by raymatos** [comment]
How about the abandon queue?  Is there a way to set the name of the queue?  Is the queue the same for all consumers? 

This is a awesome feature, just sucks that its bury in the project.

**Comment by vivri** [comment]
:+1: 
I had to dig for quite some time before I got here. I think it's important enough to be put in the README.

**Comment by grubino** [comment]
👍

**Comment by SergeATX** [comment]
You would have to create a fanout exchange first and bind it to a queue
Then you can specify the DLQ rediraction in the consume declaration:
topic(Queue.passive(
      Queue("queueName", durable = true, exclusive = false, autoDelete = false,
        arguments = Seq(
          `x-expires`(10 minutes), 
          `x-message-ttl`(5 minutes),
          `x-max-length`(10000),
          `x-max-length-bytes`(1000),
          `x-max-priority`(100),
          `x-dead-letter-exchange`("exchangeName.DLQ"),
          `x-dead-letter-routing-key`("routingKey.DLQ")
        ))),
    List("routingKey"),
    Exchange.topic("exchangeName", true, false))

**Comment by timcharper** [comment]
This is resolved with 13f41d6b4cef1644f91b9073ea5a922cf3fa881e and will be resolved in the next release of `op-rabbit`.

**Comment by timcharper** [comment]
I will close this when a link is put in the README.
