### ISSUE TITLE
codeship dependency not found - sbt assembly 

### ISSUE THREAD

**Issue by ariasf** [SpinGo/op-rabbit#58]
[info] Resolving jline#jline;2.12.1 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.thenewmotion.akka#akka-rabbitmq_2.11;2.2: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]      com.thenewmotion.akka:akka-rabbitmq_2.11:2.2
[warn]        +- com.spingo:op-rabbit-core_2.11:1.2.1

........
.
.
.
.

[error](*:update) sbt.ResolveException: unresolved dependency: com.thenewmotion.akka#akka-rabbitmq_2.11;2.2: not found
[error] Total time: 3 s, completed Feb 10, 2016 4:24:18 AM

my config file looks like this 

resolvers ++= Seq(
    "SpinGo OSS" at "http://spingo-oss.s3.amazonaws.com/repositories/releases"
)

val opRabbitVersion = "1.2.1"

libraryDependencies ++= Seq(
    "com.spingo" %% "op-rabbit-core"        % opRabbitVersion,
    "com.spingo" %% "op-rabbit-play-json"   % opRabbitVersion,
    "com.spingo" %% "op-rabbit-json4s"      % opRabbitVersion,
    "com.spingo" %% "op-rabbit-airbrake"    % opRabbitVersion,
    "com.spingo" %% "op-rabbit-akka-stream" % opRabbitVersion
)

first i was using  val opRabbitVersion = "1.2.0" so i updated to the one above 1.2.1 still get this sbt asembly error in codeship, any ideas of why this would happen?

**Comment by timcharper** [comment]
I've been mirroring akka-rabbitmq to reduce the number of sources people have to add to use `op-rabbit`. I may have forgotted to push this dependency (which I just did). Try again?

**Comment by ariasf** [comment]
Works now! Thanks a lot! this project saved me a bunch of time !

**Comment by timcharper** [comment]
Wonderful to hear it!
