### ISSUE TITLE
How to expose BasicProperties in AsyncAckingConsumer handler?

### ISSUE THREAD

**Issue by whitehead1415** [SpinGo/op-rabbit#6]
It would be useful to have access to the properties in order to get the reply-to property when handling messages.

Unless there is a different way to do the request/response pattern?

**Comment by timcharper** [comment]
Hey Michael! I've thought about this and think that Directives (a la Spray) would be the best way to implement it.

IE:

```
AsyncAckingConsumer(...) {
  (Property[ReturnAddress] & body) { (address, body) =>
    // le work
  }
}
```

And then, use the magnet pattern. Thoughts?

Tim

**Comment by whitehead1415** [comment]
Ok yeah

Thanks

**Comment by timcharper** [comment]
This is shaping up nicely.

https://github.com/SpinGo/op-rabbit/blob/dsl/core/src/test/scala/com/spingo/op_rabbit/subscription/DirectivesSpec.scala

Modeled individual properties are used to both extract values and set them again.
