### ISSUE TITLE
Does RabbitControl actor support several subscriptions ?

### ISSUE THREAD

**Issue by aomalov** [SpinGo/op-rabbit#61]
Hi !

I was trying to run several  _AckedFlows_ with the same RabbitMQ Server (with different queues, though)
_RabbitSource_ materializes to _SubscriptionRef_ and when I call _close_ on it - the top level **RabbitControl** actor is killed, so is destroyed (in turn) the parallel subscription that I have made with the same rabbitcontrol actor ref.

**My question is**: according to the **RabbitControl.scala** code - the actor maintains a list of subscriptions - so is he really meant to support parallel subscriptions (with their independent connections and channels) or not ?

Thanks in advance !

**Comment by timcharper** [comment]
The RabbitControl actor certainly does support multiple subscriptions! The toplevel RabbitControl actor shouldn't be closed when closing a subscription; if that is the case, then that's a bug and should be resolved.

**Comment by aomalov** [comment]
Thanks, Tim !

Found the one closing RabbitControl on our side. It is all clear.
