### ISSUE TITLE
Connecting to Rabbit

### ISSUE THREAD

**Issue by mvbaffa** [SpinGo/op-rabbit#65]
Is there some kind of Connection Factory so that I can connect to Rabbit without using a conf file.

Thanks

**Comment by timcharper** [comment]
@mvbaffa yes - RabbitControl accepts a ConnectionParams: http://spingo-oss.s3.amazonaws.com/docs/op-rabbit/current/index.html#com.spingo.op_rabbit.RabbitControl

``` scala
actorSystem.actorOf(Props { new RabbitControl(connectionParams) })
```

**Comment by mvbaffa** [comment]
I'am trying to reproduce you manual, so:

 val rabbitAddress =  new com.rabbitmq.client.Address("IP")
  val connectionParams = new ConnectionParams(username = "user", password = "pwd", hosts = List(rabbitAddress))
  val rabbitControl = actorSystem.actorOf(Props { new RabbitControl(connectionParams) })

It is connecting OK. But when I include the lines below I got a compiler error

  case class Person(name: String, age: Int)
  rabbitControl ! Message.queue(Person(name = "Ivanah Tinkle", age = 25), queue = "TEST_SCALA")

Error: Error:(14, 32) could not find implicit value for parameter marshaller: com.spingo.op_rabbit.RabbitMarshaller[TransactionDispatcher.Person]
  rabbitControl ! Message.queue(Person(name = "Ivanah Tinkle", age = 25), queue = "TEST_SCALA")
                               
Can you help me
