### ISSUE TITLE
Consider publishing to bintray instead of S3.

### ISSUE THREAD

**Issue by dpratt** [SpinGo/op-rabbit#68]
Bintray allows for free public maven/ivy repositories for open source projects, and offers a much simpler route to get your code into maven central than publishing to Sonatype.

Additionally, recent versions of sbt have the bintray JCenter repo added to the list of default resolvers, which would mean consumers of op-rabbit wouldn't have to add a custom resolver to their build.

I'd be happy to create a JCenter repo and send a PR with the relevant changes - I've used it for a couple other open source projects of mine, and it works quite well.

**Comment by timcharper** [comment]
I'm not sure how to create a JCenter repo, so I've opened a ticket to publish to maven central. I already publish other artifacts under a personal org.

**Comment by timcharper** [comment]
Artifacts are being published to maven central now. However, I'll need to get the upstream dependency to follow suit.
