### ISSUE TITLE
Cannot connect with username & password

### ISSUE THREAD

**Issue by emaung** [SpinGo/op-rabbit#70]
Hi, first of all, it might be me doing something wrong as I am new to both scala and rabbitmq.
I keep getting following message from the log

`[akka://default/user/$a/connection] akka://default/user/$a/connection in Disconnected received Connect: can't connect to amqp://dev@{192.168.2.224:5672}:5672/event-management, retrying in 10 seconds`

I looked up the connection url and looks like it is not using the password provided in application.conf. I used debugger to step in RabbitContol and all connections details are correctly parsed. Then I found this in "akka-rabbitmq"

`def uri: String = "amqp://%s@%s:%d/%s".format(self.getUsername, self.getHost, self.getPort, self.getVirtualHost)`

So it seems to me that the connection string is invalid. If this is the problem, then I will create an issue on that repo.

Regards

**Comment by timcharper** [comment]
Are you sure? This functionality is verified to work for me.

The curly braces are added by the logging.

**Comment by SergeyZharikhin** [comment]
actually i have the same issue.`15:32:54.526 [such-system-akka.actor.default-dispatcher-5] ERROR com.thenewmotion.akka.rabbitmq.ConnectionActor - akka://such-system/user/$a/connection in Disconnected received Connect: can't connect to amqp://guest@{127.0.0.1:15672}:5672/foo, retrying in 10 seconds
`

and my application.conf has:
```
op-rabbit {
  connection {
    virtual-host = "foo"
    hosts = ["127.0.0.1"]
    username = "guest"
    password = "guest"
    port = 15672
    ssl = false
    connection-timeout = 3s
  }
}
