### ISSUE TITLE
Isolate Op-Rabbit publishers to their own thread pool.

### ISSUE THREAD

**Issue by RibleStrype** [SpinGo/op-rabbit#77]
As per my understanding of how op-rabbit works, messages are being published by com.spingo.op_rabbit.Publisher (PublisherImpl to be specific) which in turn invokes a blocking basicPublish() on a channel. Does it mean that I should not publish messages from actors running with the default akka dispatcher? Or perhaps I should create the RabbitControl actor in with a separate dedicated dispatcher? What's the bets practice for it?

Thank in advance

**Comment by timcharper** [comment]
@RibleStrype yes, what you point out is correct, and the best practice would be to use a separate thread pool for publishing messages. A deeper analysis would need to be done for all of the places where message publishing is done (recovery mechanism, etc.). A separate thread pool should be used for these operations.

**Comment by timcharper** [comment]
Resolved with 8d2b313f6169451ec413c8db9df72caedd9b4df2, will be deployed in `1.5.0`

**Comment by timcharper** [comment]
@RibleStrype can you please review the solution and see if you spot any errors?

**Comment by RibleStrype** [comment]
Thanks for the fix, looks good!
