### ISSUE TITLE
Connection Hoarding in periodic subscribe-unsubscribe

### ISSUE THREAD

**Issue by vivri** [SpinGo/op-rabbit#78]
I have this code executing periodically (inside of a method), and op-rabbit isn't releasing any of the connections to RabbitMQ, which over time kills the Rabbit instance.

```
import ExecutionContextImplicits.ioContext
implicit val failFast = RecoveryStrategy.none

val subscription = Subscription.run(Play.current.actorSystem.actorOf(Props[RabbitControl])) {
        channel() {
          consume(Queue.passive(queueName)) {
            nack(true)
          }
        }
      }

      subscription
          .initialized
          .andThen { case _ =>
            subscription.close(1 second)
          }
```

Is it the code's fault, or is it a defect?

**Comment by vivri** [comment]
It appears that if I am to extract the RabbitControl actor into a lazy val somewhere global, there's only one connection that's maintained.

Is it by design that the subscription doesn't terminate the connection to the RabbitMQ?

I'd argue that if there are no active subscriptions to the RabbitControl actor at some point, it should close the connection.

**Comment by timcharper** [comment]
RabbitControl is intended to be instantiated as a singleton actor-per-cluster. It looks like you are allocating a new rabbitControl actor for every subscription? If so, that is an error.
