### ISSUE TITLE
Ack occured when a message is published in a queue that does not exists using ConfirmResponse

### ISSUE THREAD

**Issue by Dnomyar** [SpinGo/op-rabbit#83]
For instance, concidering the following code

``` scala
Logger.trace(s"Planning : queue $queue_name, delay $delay, the message ${message.toString}")
val res = (
  rabbitControl ? Message.queue(
    message
    , queue = queue_name
    , properties = Seq(delay).flatten
  )
).mapTo[ConfirmResponse]


res.map { r =>
  Logger.trace(s"Rabbit response : $r")
  r
}
```

Here is my logs : 

```
...
[trace] - application - Planning : queue backup_queue, delay None, the message ....
[trace] - application - Rabbit response : Ack(1)
...
```

And my rabbit queue list : 
<img width="695" alt="capture d ecran 2016-07-13 a 16 59 36" src="https://cloud.githubusercontent.com/assets/4415022/16808195/c8d379de-491b-11e6-858e-8b0932b15017.png">

The clients acks the message when  an error should be returned.
This behavior seems strange. What do you think ?

**Comment by timcharper** [comment]
The behavior is that of RabbitMQ. And, this is actually something that has gotten me before!

From https://www.rabbitmq.com/confirms.html we read:

> For unroutable messages, the broker will issue a confirm once the exchange verifies a message won't route to any queue (returns an empty list of queues). If the message is also published as mandatory, the basic.return is sent to the client before basic.ack. The same is true for negative acknowledgements (basic.nack).

I'm sure you've figured this out already, but thought I would respond just in case somebody else stumbles on this.
