### ISSUE TITLE
Doesn't seems to work with latest versions of Akka stream (tried with 2.4.7 and 2.4.8)

### ISSUE THREAD

**Issue by git-oca** [SpinGo/op-rabbit#84]
Hi, I encounter the following error when I try to use op-rabbit with latest version of akka stream :

[error](run-main-0) java.lang.NoSuchMethodError: akka.util.Helpers$.toRootLowerCase(Ljava/lang/String;)Ljava/lang/String;
java.lang.NoSuchMethodError: akka.util.Helpers$.toRootLowerCase(Ljava/lang/String;)Ljava/lang/String;
        at akka.stream.StreamSubscriptionTimeoutSettings$.apply(ActorMaterializer.scala:491)
        at akka.stream.ActorMaterializerSettings$.apply(ActorMaterializer.scala:243)
        at akka.stream.ActorMaterializerSettings$.apply(ActorMaterializer.scala:232)
        at akka.stream.ActorMaterializer$$anonfun$1.apply(ActorMaterializer.scala:41)
        at akka.stream.ActorMaterializer$$anonfun$1.apply(ActorMaterializer.scala:41)
        at scala.Option.getOrElse(Option.scala:121)
        at akka.stream.ActorMaterializer$.apply(ActorMaterializer.scala:41)

The compilation work fine, but while runtime, this occurs when try to instanciate the Actor materializer with :"implicit val materializer = ActorMaterializer()"

Note that when if recompile op-rabbit using akka 2.4.7 or 2.4.8, the error is gone.

**Comment by timcharper** [comment]
Akka must have broken ABI compatibility, or you have heterogenous versions of Akka loaded?

**Comment by git-oca** [comment]
I also think something changed in Materializer since version 2.4.2...
To reproduce the problem, you can just use that Main.scala :

``` scala
import akka.actor.ActorSystem
import akka.stream.ActorMaterializer

object Main {
  def main (args : Array[String]) : Unit =  {
    implicit val system = ActorSystem("MainSystem")
    implicit val materializer = ActorMaterializer()

    println ("Test")    

  }
}
```

and that build.sbt :

``` scala
name := "xxx"

version       := "0.1-SNAPSHOT"

scalaVersion  := "2.11.8"


libraryDependencies ++= {
  val opRabbitVersion = "1.3.0"
  val akkaV = "2.4.8"
  Seq(

   "com.spingo" %% "op-rabbit-core"        % opRabbitVersion,
   "com.spingo" %% "op-rabbit-play-json"   % opRabbitVersion,
   "com.spingo" %% "op-rabbit-json4s"      % opRabbitVersion,
   "com.spingo" %% "op-rabbit-airbrake"    % opRabbitVersion,
   "com.spingo" %% "op-rabbit-akka-stream" % opRabbitVersion,


   "com.typesafe.akka" %% "akka-stream" % akkaV,
   "com.typesafe.akka" %% "akka-http-experimental" % akkaV,
   "commons-logging" % "commons-logging" % "1.1.1" 

  )
}

resolvers ++= Seq(
    "SpinGo OSS" at "http://spingo-oss.s3.amazonaws.com/repositories/releases"
)
```

"sbt run" will fail like that :

```
$ sbt run
[info] Set current project to xxx (in build file:/C:/cygwin64/home/carnalo/dev/rabbit/)
[info] Updating {file:/C:/cygwin64/home/carnalo/dev/rabbit/}rabbit...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Compiling 1 Scala source to C:\cygwin64\home\carnalo\dev\rabbit\target\scala-2.11\classes...
[info] Running Main
[error] (run-main-0) java.lang.NoSuchMethodError: akka.util.Helpers$.toRootLowerCase(Ljava/lang/String;)Ljava/lang/String;
java.lang.NoSuchMethodError: akka.util.Helpers$.toRootLowerCase(Ljava/lang/String;)Ljava/lang/String;
...
...
```

If you then comment the com.spingo dependencies in build.sbt, the program will work fine. Weird is it ? So I think some internal stuff using some kind of reflexion in the Materializer don't work well with com.spingo but I don't know why.

**Comment by juanpavergara** [comment]
I'm running a very simple program with akka-streams 2.4.9 and op-rabbit 1.3 and it's working fine. The program is nothing else than the one in the README.MD

``` scala
import akka.stream._
import akka.actor.{Props, ActorSystem}
import com.spingo.op_rabbit.{SubscriptionRef, HListToValueOrTuple, RabbitControl, Directives}
import com.spingo.op_rabbit.stream.RabbitSource
import shapeless.{HNil, ::}

object ApplicationMain extends App {

implicit val system = ActorSystem("QuickStart")
implicit val materializer = ActorMaterializer()

val rabbitControl = system.actorOf(Props[RabbitControl])

  import Directives._
  val r = RabbitSource(
    rabbitControl,
    channel(qos = 3),
    consume(queue(
      "such-queue",
      durable = true,
      exclusive = false,
      autoDelete = false)),
    body(as[String]))

  r.runForeach { s =>
        println(s)
      } 
}
```

My build.sbt goes like 

``` scala
name := """scala_school_akka_streams"""

version := "1.0"

scalaVersion := "2.11.7"

val opRabbitVersion = "1.3.0"

libraryDependencies ++= Seq(
  "com.typesafe.akka" %% "akka-actor" % "2.4.9",
  "com.typesafe.akka" %% "akka-stream" % "2.4.9",
  "com.spingo" %% "op-rabbit-core" % opRabbitVersion,
  "com.spingo" %% "op-rabbit-akka-stream" % opRabbitVersion,
  "com.typesafe.akka" %% "akka-testkit" % "2.3.11" % "test",
  "org.scalatest" %% "scalatest" % "2.2.4" % "test")

```

@git-oca git version 2.4.9 a try :)

**Comment by git-oca** [comment]
@juanpavergara : thanks for your message, but that still don't work for me, even with version 2.4.9
In your build.sbt, do you have a resolver like this one ? 

```
resolvers ++= Seq(
    "SpinGo OSS" at "http://spingo-oss.s3.amazonaws.com/repositories/releases"
)
```

If not were does the jar for com.spingo comes from ?

**Comment by juanpavergara** [comment]
@git-oca I didn't have the resolver and the jar was coming from my local repo because I've been playing with the library in a previous project. I have added the resolver and updated the build.sbt and it is still working :/

The build.sbt now goes like

``` scala
name := """scala_school_akka_streams"""

version := "1.0"

scalaVersion := "2.11.7"

resolvers ++= Seq(
  "SpinGo OSS" at "http://spingo-oss.s3.amazonaws.com/repositories/releases"
)

val opRabbitVersion = "1.3.0"

libraryDependencies ++= Seq(
  "com.typesafe.akka" %% "akka-actor" % "2.4.9",
  "com.typesafe.akka" %% "akka-stream" % "2.4.9",
  "com.spingo" %% "op-rabbit-core" % opRabbitVersion,
  "com.spingo" %% "op-rabbit-akka-stream" % opRabbitVersion,
  "com.typesafe.akka" %% "akka-testkit" % "2.3.11" % "test",
  "org.scalatest" %% "scalatest" % "2.2.4" % "test")
```

try adding

``` scala
"com.typesafe.akka" %% "akka-actor" % "2.4.9"
```

to your dependencies.

**Comment by juanpavergara** [comment]
@git-oca try adding 
```scala
"com.typesafe.akka" %% "akka-actor" % "2.4.9",
```
to your dependencies.

**Comment by git-oca** [comment]
@juanpavergara : Thanks, that work for me, including "com.typesafe.akka" %% "akka-actor" % "2.4.9"
makes everthing working fine !
