### ISSUE TITLE
Add a way to connect to multiple RabbitMQ clusters

### ISSUE THREAD

**Issue by urcadox** [SpinGo/op-rabbit#90]
Hello,

There is a missing feature in this otherwise great client: the possiblity to connect to multiple clusters.

A way to instantiate a RabbitControl with a parameter to set the base config name would be fine (set to "op-rabbit" by default).

Thoughts?

**Comment by timcharper** [comment]
This is possible right now. You can instantiate RabbitControl actor with ConnectionParams object, and `connectionParams.fromConfig` accepts a config object (which you can pull from anywhere in the config tree, defaulting to `op-rabbit.connection`).

**Comment by timcharper** [comment]
See https://github.com/SpinGo/op-rabbit/wiki/Cookbook

**Comment by urcadox** [comment]
Oh great, thanks. Did not see that.

Le dim. 4 sept. 2016 à 23:11, Tim Harper notifications@github.com a
écrit :
