### ISSUE TITLE
Can't configure default dead letter exchange when using RecoveryStrategy.limitedRedeliver

### ISSUE THREAD

**Issue by beethovenklc** [SpinGo/op-rabbit#92]
Using default exchange "" forces me to configure my user to have write access to "amq.default", which is undesirable. If I could change the dead letter exchange I'll solve this security issue I have.

I suggest adding a new parameter to function RecoveryStrategy.limitedRedeliver called dlx: String = "", and replace the empty string used below with this parameter.

**Comment by timcharper** [comment]
Addressed with 7ad80c7; will be released soon

**Comment by SergeATX** [comment]
@timcharper In this change on lines 75 there is publish to default exchange and on line 156 the exchange for abandon queue is default as well.

Do I miss something, or it will go do default exchange and fail for user that doesn't have permissions on default exchange?

**Comment by timcharper** [comment]
Oh, I see. :/

What is really needed is the ability to provide your own binding generation function. If you're not publishing using the default exchange, then you must create a new binding in addition to creating the queue.

I'm worried about supporting too many configurations as part of the benefit of using the library is it makes many decisions for you (that for most people are good defaults). I can break this up into a class which you can extend and override with your own binding factory without changing the existing API. Then we can revisit the API in a future release when we break compatibility again.

**Comment by timcharper** [comment]
Does bf72761510c309389edb4e1f7bf002592cc5758c help?

It's released in `1.6.0-RC1`.

**Comment by SergeATX** [comment]
On lines     178 and 79 you are still publishing to default exchange, even after declaring the direct binding on custom exchange.
On line 162 you are defining the abandon exchange  to default exchange.
It is improvement, but the code will need to use provided custom exchange and a routing key to completely avoid publishing anything to default exchange

Hope it helps.
BTW Thanks a lot for your work, you made really awesome library!

**Comment by timcharper** [comment]
Oh my, that's embarrassing. I whipped it up quickly and didn't write a test. :/ Thanks for catching it. Try `1.6.0-RC2`.

**Comment by SergeATX** [comment]
Looks perfect @timcharper 

Thanks a lot for your help.
BTW, remember I complained about not being able to publish to newly created topic queue - [https://github.com/SpinGo/op-rabbit/issues/91] ? It has similar issue, the library is trying to publish to default exchange with the queue name as routing key :)

**Comment by beethovenklc** [comment]
Thank you very much @timcharper

**Comment by timcharper** [comment]
@shizafon Oh! I see! Thanks for bringing it up again.

I have never used rabbitMQ with security configured that way, so I didn't really have that use case in mind when I was writing the library. That doesn't mean it isn't a valid use case, though! I'm sorry you've experienced pain and frustration here here.

There are a few options:

`Message.topic(body, routingKey, exchangeName)`

or

```
val myExchangePublisher = Publisher.exchange(exchange)
Message(body, myExchangePublisher)
```

Reusing the `exchangePublisher` is encouraged as otherwise op-rabbit will declare the publisher every message, and that will slow down throughput, overall.

**Comment by SergeATX** [comment]
Thanks @timcharper.
I am using that suggested approach: `Message.topic(body, routingKey, exchangeName)`
