### ISSUE TITLE
akka-rabbitmq dependency not found for op-rabbit 1.4.0

### ISSUE THREAD

**Issue by svezfaz** [SpinGo/op-rabbit#94]
Getting a downstream dependency error when migrating from 1.3.0 to 1.4.0

`sbt.ResolveException: unresolved dependency: com.thenewmotion.akka#akka-rabbitmq_2.11;2.3: not found`

Might be the same solution as for https://github.com/SpinGo/op-rabbit/issues/58 ?

**Comment by timcharper** [comment]
Thank you for the report. And, sorry about this. Those guys are working on getting the plugin on maven and I didn't realize it wasn't done yet. I'll push a copy to the spingo resolver to help relieve the pain in the meantime.

**Comment by svezfaz** [comment]
Looks fine now, thanks a lot!
