### ISSUE TITLE
consumer cannot receive further messages after the queue is created

### ISSUE THREAD

**Issue by sagargit2** [SpinGo/op-rabbit#95]
I am using the **CloudAMPQ service and its management console.**
In the example for consumer shown here,  [op-rabbit example using op-rabbit-play-json](https://github.com/sagargit2/op-rabbit/blob/master/README.md) ,
**The consumer creates the queue and bindings for the first time when I run that example. But, when I run for the second time, the consumer cannot receive the message.**
I also tried to consume by using`Queue.passive()` , but its not working.
**The consumer can get the message only for the first time when the queue is created.**

**Comment by timcharper** [comment]
@sagargit2 this is very surprising. The test in 63bbc19fa79f493c503186a7de0f90d3f8435a1b shows that this functionality works.

Binding failures are propagated to the `initialized` Future on the returned subscription. Can you check to see if that Future fails, and what is the resulting error?
